### ISSUE TITLE
validation by RTX-3090

### ISSUE THREAD

**Issue by handworker** [Ghostish/BAT#10]
Hi,
Maybe I can provide another validation by using the provided pre-trained bat_kitti_cat.cpkt model:

DATALOADER:0 VALIDATE RESULTS
{'precision/test': 76.09471893310547,
'precision/test_epoch': 76.09471893310547,
'success/test': 63.18337321281433,
'success/test_epoch': 63.18337321281433}

Environment: Cuda-11.0; PyTorch: 1.7.0; RTX 3090;

It seems that the success result is better and the precision is slightly inferior to the original result reported in Table 1 of the paper. Is it correct?

**Comment by Ghostish** [comment]
This is due to CUDA 11.0. Please consider using CUDA 10.x.
See also #5 #6 .

**Comment by handworker** [comment]
> This is due to CUDA 11.0. Please consider using CUDA 10.x.
> See also #5 #6 .

Hi,
It seems that CUDA 11.0 doesn't lead too much performance drop. For the obtained success result (63.18337321281433), I am confused that why does it significantly outperform the reported car success (**60.5**) in Table 1 of the paper. Could you please explain about it?

Thanks a lot.

**Comment by Ghostish** [comment]
As said in https://github.com/Ghostish/BAT#reproduction, this codebase produces better results than those we report in our original paper. We will update the results in our paper soon.

**Comment by handworker** [comment]
> As said in https://github.com/Ghostish/BAT#reproduction, this codebase produces better results than those we report in our original paper. We will update the results in our paper soon.

Okay, thanks.
