### ISSUE TITLE
Tracking all objects

### ISSUE THREAD

**Issue by YoushaaMurhij** [Ghostish/BAT#12]
Nice work!
Can we use this method to track all the objects in the scene?. I mean generate IDs for all the bboxes that we feed to the network.
Could you please share your visualization script?

Thanks!

**Comment by Ghostish** [comment]
Yes, it can be used to track multiple objects at the same time if you feed multiple target template to the model. However, this is different with another topic “Multiple Object Tracking”, where there are no **targets** at the first frame. 

The release of the visualization script is in our plan and we will release it in the future.
