### ISSUE TITLE
Testing InNuScenes

### ISSUE THREAD

**Issue by StrivedTye** [Ghostish/BAT#16]
Hi,
Thanks for your work.

I try to test the results on Nuscenes, but the total number of frame is different from your value reported in paper. For example, "Bus"  includes 2953 frames when testing, and 2215 in paper. I don't why. Can you give me some tips?
![image](https://user-images.githubusercontent.com/19620650/138588232-80bf66c9-9d19-4ccb-a9fc-8d012051f6b8.png)

Thanks.

**Comment by Ghostish** [comment]
We already updated our main paper in ArXiv.For reproduction,  please refer to the experiment setup and results in that latest version.
