### ISSUE TITLE
你好，请问可以发一下numpy和pomegranate版本吗？

### ISSUE THREAD

**Issue by Qinwjie** [Ghostish/BAT#19]

**Comment by Qinwjie** [comment]
在安装中我还出现了这个问题，可以帮忙看看吗：
ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda3\envs\bat\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\qin\\AppData\\Local\\Temp\\pip-install-_p727fcs\\pointnet2-ops_f65ede3748624033908866462af6d5a6\\pointnet2_ops_lib\\setup.py'"'"'; __file__='"'"'C:\\Users\\qin\\AppData\\Local\\Temp\\pip-install-_p727fcs\\pointnet2-ops_f65ede3748624033908866462af6d5a6\\pointnet2_ops_lib\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\qin\AppData\Local\Temp\pip-wheel-pr0vsdpf'
       cwd: C:\Users\qin\AppData\Local\Temp\pip-install-_p727fcs\pointnet2-ops_f65ede3748624033908866462af6d5a6\pointnet2_ops_lib
  Complete output (970 lines):
  信息: 用提供的模式无法找到文件。

**Comment by Ghostish** [comment]
I am using numpy 1.21.2 and pomegranate 0.14.7. 
However, the logs show that you get this problem when installing `pointnet2_ops_lib`.  I haven't tested this on windows and you probably should install these packages on Linux.

**Comment by lichengqi0805** [comment]
python 3.6 is incompatible with numpy 1.21.2

**Comment by chenqi13814529300** [comment]
> 在安装中我还出现了这个问题，可以帮忙看看吗： ERROR: Command errored out with exit status 1: command: 'D:\Anaconda3\envs\bat\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\qin\AppData\Local\Temp\pip-install-_p727fcs\pointnet2-ops_f65ede3748624033908866462af6d5a6\pointnet2_ops_lib\setup.py'"'"'; **file**='"'"'C:\Users\qin\AppData\Local\Temp\pip-install-_p727fcs\pointnet2-ops_f65ede3748624033908866462af6d5a6\pointnet2_ops_lib\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\qin\AppData\Local\Temp\pip-wheel-pr0vsdpf' cwd: C:\Users\qin\AppData\Local\Temp\pip-install-_p727fcs\pointnet2-ops_f65ede3748624033908866462af6d5a6\pointnet2_ops_lib Complete output (970 lines): 信息: 用提供的模式无法找到文件。

**Comment by chenqi13814529300** [comment]
> 在安装中我还出现了这个问题，可以帮忙看看吗： ERROR: Command errored out with exit status 1: command: 'D:\Anaconda3\envs\bat\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\qin\AppData\Local\Temp\pip-install-_p727fcs\pointnet2-ops_f65ede3748624033908866462af6d5a6\pointnet2_ops_lib\setup.py'"'"'; **file**='"'"'C:\Users\qin\AppData\Local\Temp\pip-install-_p727fcs\pointnet2-ops_f65ede3748624033908866462af6d5a6\pointnet2_ops_lib\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\qin\AppData\Local\Temp\pip-wheel-pr0vsdpf' cwd: C:\Users\qin\AppData\Local\Temp\pip-install-_p727fcs\pointnet2-ops_f65ede3748624033908866462af6d5a6\pointnet2_ops_lib Complete output (970 lines): 信息: 用提供的模式无法找到文件。

我也遇到这种问题了，你是怎么解决的
