### ISSUE TITLE
when will the code be released？

### ISSUE THREAD

**Issue by wangkai602058765** [Ghostish/BAT#2]
Congratulations！I am quite interested in your work. I want to know when will the code be released? thank you!

**Comment by Ghostish** [comment]
We are refactoring the codes to make them clearer and easier to use. The work is almost finished and we will release the codes after sufficient tests.

**Comment by wangkai602058765** [comment]
> We are refactoring the codes to make them clearer and easier to use. The work is almost finished and we will release the codes after sufficient tests.

ok， thank you！
