### ISSUE TITLE
my test results is 29.8/25.4(prec/succ)

### ISSUE THREAD

**Issue by StrivedTye** [Ghostish/BAT#6]
Hello. Thanks for your great work.
my test results is 29.8/25.4(prec/succ)
![image](https://user-images.githubusercontent.com/19620650/131664732-78a9dc3b-c696-4323-89e7-3bdfd7fd99b2.png)
 my env is python3.8, pytorch1.8.1, cuda11.1, cudnn8, with 2080ti.

**Comment by Ghostish** [comment]
This issue is duplicated.
Please check another #5 to get more information.

It seems that there is some problem with a higher version Pytorch/Python. Could you train the model from scratch and report your results? It would be helpful.

**Comment by StrivedTye** [comment]
> This issue is duplicated.
> Please check another #5 to get more information.
> 
> It seems that there is some problem with a higher version Pytorch/Python. Could you train the model from scratch and report your results? It would be helpful.

Hi, I retain the model on a env with pytorch1.9.0, and got the following results :
![image](https://user-images.githubusercontent.com/19620650/131767137-09b96cca-b2bc-46e0-a493-9460cb239bd9.png)
The two metrics also are around 29.0/25.0 :(
By the way, when runing the code in this env, it will give a warnning:
    RuntimeWarning: invalid value encountered in Add:   in self.points[i, :] = self.points[i, :] + x[i]

Thank you very much.

**Comment by Ghostish** [comment]
> > This issue is duplicated.
> > Please check another #5 to get more information.
> > It seems that there is some problem with a higher version Pytorch/Python. Could you train the model from scratch and report your results? It would be helpful.
> 
> Hi, I retain the model on a env with pytorch1.9.0, and got the following results :
> ![image](https://user-images.githubusercontent.com/19620650/131767137-09b96cca-b2bc-46e0-a493-9460cb239bd9.png)
> The two metrics also are around 29.0/25.0 :(
> By the way, when runing the code in this env, it will give a warnning:
> RuntimeWarning: invalid value encountered in Add: in self.points[i, :] = self.points[i, :] + x[i]
> 
> Thank you very much.

 I re-tested the pretrained model with Python3.8 and Pytorch 1.91 Cuda10.2 but I could not reproduce the bug/warning above. 
Is your dataset correctly configured? Could you print out some value in `n self.points[i, :] = self.points[i, :] + x[i]` ?  How many sequences/frames do you use to train/test the model?  More information will be appreciated.

**Comment by Ghostish** [comment]
The test result is the **same** as reported when I use Pytorch 1.9.1 and **CUDA 10.2**.
It drops a little bit when I switch to Pytorch 1.9.1 with **CUDA 11.1**.  
![image](https://user-images.githubusercontent.com/7406087/131787683-21abbf5b-ff73-4d76-aef6-7bc721ca9d4b.png)
It is likely that the CUDA version affects reproducibility. But the performance gap is minor and one can re-train the model to reach the reported results.  It seems that there are some other issues with your environment.

For the dataset, the size of your generated `.dat` file for the train split doesn't match mine:
![image](https://user-images.githubusercontent.com/7406087/131787875-9d6de904-376b-4b12-ad51-894c2e6a7819.png)

Can you report the value when you encounter the `RuntimeWarning: invalid value encountered in Add: in self.points[i, :] = self.points[i, :] + x[i]` ?

**Comment by StrivedTye** [comment]
> The test result is the **same** as reported when I use Pytorch 1.9.1 and **CUDA 10.2**.
> It drops a little bit when I switch to Pytorch 1.9.1 with **CUDA 11.1**.
> ![image](https://user-images.githubusercontent.com/7406087/131787683-21abbf5b-ff73-4d76-aef6-7bc721ca9d4b.png)
> It is likely that the CUDA version affects reproducibility. But the performance gap is minor and one can re-train the model to reach the reported results. It seems that there are some other issues with your environment.
> 
> For the dataset, the size of your generated `.dat` file for the train split doesn't match mine:
> ![image](https://user-images.githubusercontent.com/7406087/131787875-9d6de904-376b-4b12-ad51-894c2e6a7819.png)
> 
> Can you report the value when you encounter the `RuntimeWarning: invalid value encountered in Add: in self.points[i, :] = self.points[i, :] + x[i]` ?

Hi, I print the 'x', and the RuntimeWarning is as follows:
![image](https://user-images.githubusercontent.com/19620650/131804598-25630b61-8954-45cf-abab-3a5ae1477feb.png)

**Comment by StrivedTye** [comment]
> The test result is the **same** as reported when I use Pytorch 1.9.1 and **CUDA 10.2**.
> It drops a little bit when I switch to Pytorch 1.9.1 with **CUDA 11.1**.
> ![image](https://user-images.githubusercontent.com/7406087/131787683-21abbf5b-ff73-4d76-aef6-7bc721ca9d4b.png)
> It is likely that the CUDA version affects reproducibility. But the performance gap is minor and one can re-train the model to reach the reported results. It seems that there are some other issues with your environment.
> 
> For the dataset, the size of your generated `.dat` file for the train split doesn't match mine:
> ![image](https://user-images.githubusercontent.com/7406087/131787875-9d6de904-376b-4b12-ad51-894c2e6a7819.png)
> 
> Can you report the value when you encounter the `RuntimeWarning: invalid value encountered in Add: in self.points[i, :] = self.points[i, :] + x[i]` ?

Hi, I have found the bug, it is because the point cloud data in the 'Velodeny' was damaged in transit. Actually this is the last possibility I can imagine. But it is really due to it. Anyway, thanks for your patience.
 The test results are as follows:
<img width="192" alt="1630586239(1)" src="https://user-images.githubusercontent.com/19620650/131845931-28a7276e-86e0-4afd-8ae3-c328fed8a667.png">
Thanks!
