### ISSUE TITLE
nuscenes dataset

### ISSUE THREAD

**Issue by Chuanbo-Yu** [Ghostish/BAT#8]
I've been following your work for a long time. Thank you very much for your generous sharing of code. The code is about Kitti dataset. I don't know if the relevant code of Nuscenes dataset will be published

**Comment by Ghostish** [comment]
The NuScenes code will be released in a few weeks.  Currently we are
running some tests to make sure that the results are reproducable. Stay
tuned.

Chuanbo-Yu ***@***.***>于2021年9月10日 周五上午9:11写道：

**Comment by Ghostish** [comment]
Hi there, the code for NuScenes is just released.
